### ISSUE TITLE
ChipSystem Exception

### ISSUE THREAD

**Issue by GamezMan** [Centauri2442/VRCBlackjack#1]
Hi, Im trying to use the Blackjack system, but whenever I try to update my test world, it pops up with errors concerning the Blackjack table. It seems to be related to the chip system, but I am not certain? Is there anyway around this, because with it, I can't even go through the uploading process for worlds.
![Blackjack error](https://user-images.githubusercontent.com/85522418/213893983-32a482c3-467b-4d0a-b227-cfe1e5ab2f9c.png)

**Comment by Centauri2442** [comment]
That is actually an issue that only shows up when building and uploading, and does not happen both when ingame and when using clientsim. You can get around being able to not upload by turning off Error Pause in the console tab of the unity editor.

**Comment by GamezMan** [comment]
Oh awesome, thank you very much, looking forward to playing BlackJack
