### ISSUE TITLE
(Suggestion) add different card games?

### ISSUE THREAD

**Issue by InuYasha86000** [Centauri2442/VRCBlackjack#2]
keep in mind, this is coming from a newbie to VRchat world creation so I apologize if this would be too hard to implement, but having different card games be available to set per table such as poker, 21, maybe some basic card games as well like uno or other multiplayer card games.
it's just a thought as I haven't come across many myself. thank you for the work of putting this together though.

**Comment by Centauri2442** [comment]
Apologies, but there is currently no plans to expand on the existing systems. While I would like to both refactor the existing code and add support for other card games, I just don't have the free time to set aside for it.
